"""Change created_at to TIMESTAMP WITH TIME ZONE

Revision ID: 12d438dca1cf
Revises: bf832acea034
Create Date: 2026-10-06 22:47:42.743412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d438dca1cf'
down_revision: Union[str, Sequence[str], None] = 'bf832acea034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
