"""Change created_at to TIMESTAMP WITH TIME ZONE

Revision ID: 6c8cb637a739
Revises: 12d438dca1cf
Create Date: 2026-10-06 22:51:39.751782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8cb637a739'
down_revision: Union[str, Sequence[str], None] = '12d438dca1cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
